name: Microservices CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, account-service]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Lint Check (Spotless)
        run: |
          cd ${{ matrix.service }}
          mvn spotless:check

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        service: [user-service, account-service]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate project
        run: |
          cd ${{ matrix.service }}
          mvn validate
      - name: Compile project
        run: |
          cd ${{ matrix.service }}
          mvn compile
      - name: Package project
        run: |
          cd ${{ matrix.service }}
          mvn package -DskipTests=true
      - name: Run Unit Tests
        run: |
          cd ${{ matrix.service }}
          mvn test -DskipITs=true
      - name: Run Integration Tests
        run: |
          cd ${{ matrix.service }}
          mvn verify -DskipTests=true
      - name: Run Spotless Check
        run: |
          cd ${{ matrix.service }}
          mvn spotless:check
      - name: Run Spotless Apply
        run: |
          cd ${{ matrix.service }}
          mvn spotless:apply
      - name: Run Jacoco Report
        run: |
          cd ${{ matrix.service }}
          mvn jacoco:report  
      - name: Create Hello World HTML
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Hello World</title>
          </head>
          <body>
            <h1>Hello, World!</h1>
          </body>
          </html>' > index.html
      - name: Upload coverage and hello world files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            target/site/jacoco/jacoco.xml
            target/site/jacoco/index.html
            ${{ matrix.service}}-index.html 
      
      